apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: jaskeerat/webserver:HPA-v1
        env:
          - name: PORT
            value: "3000"
          - name: RABBIT_USERNAME
            value: guest
          - name: RABBIT_PASSWORD
            value: guest
          - name: RABBIT_HOST
            value: rabbit-mq
          - name: RABBIT_PORT
            value: "5672"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  type: ClusterIP
  selector:
    app: web-server
  ports:
  - port: 3000
    targetPort: 3000
    name: "web-server"