apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
spec:
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5672
            - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
spec:
  selector:
    app: rabbit-mq
  ports:
    - port: 5672
      targetPort: 5672
      name: "rabbit"
    - port: 15672
      targetPort: 15672
      name: "rabbit-mgmt-int"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-mgmt
spec:
  type: NodePort
  selector:
    app: rabbit-mq
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30011
      name: "rabbit-mgmt"