apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-scaler
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  metrics:
    - type: External
      external:
        metric:
          name: rabbitmq_queue_length
        target:
          type: Value
          value: "20"